backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-inventory
    tag: e966d44bf2cf3d803b9f04000af502ab9ea707bc

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
