backend:
  image:
    repository: jakecoop17/yas-inventory
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
