apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dev-strict-mtls
  namespace: dev
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dev-storefront-bff-ingress-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-bff
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dev-backoffice-bff-ingress-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-bff
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dev-media-ingress-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dev-swagger-ui-ingress-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: swagger-ui
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: dev-default-istio-mutual
  namespace: dev
spec:
  host: "*.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: dev-default-istio-mutual-global
  namespace: istio-system
spec:
  exportTo:
    - "*"
  host: "*.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: search-retry-policy
  namespace: dev
spec:
  hosts:
    - search.dev.svc.cluster.local
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: search.dev.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error,reset
      timeout: 10s
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: search-allow-product-and-storefront-bff
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: search
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/product
              - cluster.local/ns/dev/sa/storefront-bff
      to:
        - operation:
            ports:
              - "80"
              - "8090"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: product-allow-storefront-bff
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/storefront-bff
              - cluster.local/ns/dev/sa/backoffice-bff
              - cluster.local/ns/dev/sa/order
              - cluster.local/ns/dev/sa/sampledata
      to:
        - operation:
            ports:
              - "80"
              - "8090"
