backend:
  image:
    repository: jakecoop17/yas-search
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
