backend:
  image:
    repository: jakecoop17/yas-product
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
