backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-promotion
    tag: 12bb9ca74d2901c9abee3ab88b98c751f113beaf

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
