backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-promotion
    tag: e966d44bf2cf3d803b9f04000af502ab9ea707bc

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
