backend:
  image:
    repository: jakecoop17/yas-promotion
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
