backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-recommendation
    tag: e966d44bf2cf3d803b9f04000af502ab9ea707bc

  nameOverride: recommendation
  fullnameOverride: recommendation
  databaseName: recommendation
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-openai-api-key-secret
  extraVolumes:
    - name: recommendation-application
      configMap:
        name: recommendation-application-configmap
  extraVolumeMounts:
    - name: recommendation-application
      mountPath: /opt/yas/recommendation
  extraApplicationConfigPaths:
    - /opt/yas/recommendation/recommendation-application.yaml
