backend:
  image:
    repository: jakecoop17/yas-location
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: false
