apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-backoffice-bff-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/backoffice-bff
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-backoffice-ui-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/backoffice-ui
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-cart-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/cart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-customer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/customer
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-inventory-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/inventory
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-location-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/location
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-media-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/media
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-order-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/order
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-payment-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/payment
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-payment-paypal-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/payment-paypal
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-product-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/product
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-promotion-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/promotion
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-rating-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/rating
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-recommendation-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/recommendation
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-sampledata-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/sampledata
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-search-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/search
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-storefront-bff-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/storefront-bff
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-storefront-ui-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/storefront-ui
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-swagger-ui-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/swagger-ui
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-tax-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/tax
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-webhook-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/webhook
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-yas-configuration-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: env-dev
    path: k8s/charts/yas-configuration
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
