apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-configuration
  namespace: argocd
spec:
  project: yas-infrastructure
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: codex/gke-infra-argocd
    path: k8s/charts/yas-configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: yas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-bff
  namespace: argocd
spec:
  project: yas-infrastructure
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: codex/gke-infra-argocd
    path: k8s/charts/storefront-bff
    helm:
      parameters:
        - name: backend.ingress.host
          value: storefront.yas.local.com
  destination:
    server: https://kubernetes.default.svc
    namespace: yas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-ui
  namespace: argocd
spec:
  project: yas-infrastructure
  source:
    repoURL: https://github.com/JakeConal/yas.git
    targetRevision: codex/gke-infra-argocd
    path: k8s/charts/storefront-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: yas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
