backend:
  image:
    repository: jakecoop17/yas-payment
    tag: d51429971ef6bd3f47299f979bc55d6fbb13757e

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment
  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml