backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-media
    tag: 12bb9ca74d2901c9abee3ab88b98c751f113beaf

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
    - name: media-images
      persistentVolumeClaim:
        claimName: media-images
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
    - name: media-images
      mountPath: /images
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

imageStorage:
  enabled: true
  size: 1Gi
  storageClassName: standard

