backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-tax
    tag: e966d44bf2cf3d803b9f04000af502ab9ea707bc

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
