backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-tax
    tag: 12bb9ca74d2901c9abee3ab88b98c751f113beaf

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
